parameters:
    coppermind_resourcespace.default_tenant_code: '%env(string:COPPERMIND_DEFAULT_TENANT_CODE)%'
    coppermind_resourcespace.base_uri: '%env(string:RESOURCE_SPACE_BASE_URI)%'
    coppermind_resourcespace.internal_base_uri: '%env(string:RESOURCE_SPACE_INTERNAL_BASE_URI)%'
    coppermind_resourcespace.api_user: '%env(string:RESOURCE_SPACE_API_USER)%'
    coppermind_resourcespace.api_key: '%env(string:RESOURCE_SPACE_API_KEY)%'
    coppermind_resourcespace.search_template: '%env(string:RESOURCE_SPACE_SEARCH_TEMPLATE)%'
    coppermind_resourcespace.default_attribute_code: '%env(string:RESOURCE_SPACE_DEFAULT_ATTRIBUTE_CODE)%'
    coppermind_resourcespace.search_limit: '%env(int:RESOURCE_SPACE_SEARCH_LIMIT)%'
    coppermind_resourcespace.timeout_seconds: '%env(int:RESOURCE_SPACE_TIMEOUT_SECONDS)%'
    coppermind_resourcespace.writeback_enabled: '%env(bool:RESOURCE_SPACE_WRITEBACK_ENABLED)%'
    coppermind_resourcespace.writeback_identifier_field: '%env(string:RESOURCE_SPACE_WRITEBACK_IDENTIFIER_FIELD)%'
    coppermind_resourcespace.writeback_uuid_field: '%env(string:RESOURCE_SPACE_WRITEBACK_UUID_FIELD)%'
    coppermind_resourcespace.writeback_owner_type_field: '%env(string:RESOURCE_SPACE_WRITEBACK_OWNER_TYPE_FIELD)%'
    coppermind_resourcespace.writeback_links_field: '%env(string:RESOURCE_SPACE_WRITEBACK_LINKS_FIELD)%'
