#!/usr/bin/env bash

set -euo pipefail

usage() {
  echo "Usage: bash scripts/aws-epic-deploy.sh <public-ip-or-url>" >&2
  exit 1
}

if [[ $# -ne 1 ]]; then
  usage
fi

TARGET="$1"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
AWS_REGION="${AWS_REGION:-us-west-2}"
DEPLOY_PARAMETER_PREFIX="${DEPLOY_PARAMETER_PREFIX:-}"
RUNTIME_USER="${BOOTSTRAP_USER:-${SUDO_USER:-${USER:-}}}"
RESOURCE_SPACE_TENANT_CODE="${RESOURCE_SPACE_TENANT_CODE:-default}"
COPPERMIND_DEFAULT_TENANT_CODE_VALUE="${COPPERMIND_DEFAULT_TENANT_CODE_VALUE:-default}"
RESOURCE_SPACE_ADMIN_USERNAME_VALUE="${RESOURCE_SPACE_ADMIN_USERNAME_VALUE:-admin}"
RESOURCE_SPACE_ADMIN_FULLNAME_VALUE="${RESOURCE_SPACE_ADMIN_FULLNAME_VALUE:-Operator DAM Admin}"
RESOURCE_SPACE_ADMIN_EMAIL_VALUE="${RESOURCE_SPACE_ADMIN_EMAIL_VALUE:-jorgen@epicglobalinc.com}"
RESOURCE_SPACE_APPLICATION_NAME_VALUE="${RESOURCE_SPACE_APPLICATION_NAME_VALUE:-Operator Assets}"
RESOURCE_SPACE_EMAIL_FROM_VALUE="${RESOURCE_SPACE_EMAIL_FROM_VALUE:-no-reply@epicglobalinc.com}"
RESOURCE_SPACE_EMAIL_NOTIFY_VALUE="${RESOURCE_SPACE_EMAIL_NOTIFY_VALUE:-jorgen@epicglobalinc.com}"
RESOURCE_SPACE_SEARCH_TEMPLATE_VALUE="${RESOURCE_SPACE_SEARCH_TEMPLATE_VALUE:-akeneo_links:%s}"
RESOURCE_SPACE_SEARCH_LIMIT_VALUE="${RESOURCE_SPACE_SEARCH_LIMIT_VALUE:-24}"
RESOURCE_SPACE_TIMEOUT_SECONDS_VALUE="${RESOURCE_SPACE_TIMEOUT_SECONDS_VALUE:-20}"
RESOURCE_SPACE_WRITEBACK_IDENTIFIER_FIELD_VALUE="${RESOURCE_SPACE_WRITEBACK_IDENTIFIER_FIELD_VALUE:-akeneo_identifier}"
RESOURCE_SPACE_WRITEBACK_UUID_FIELD_VALUE="${RESOURCE_SPACE_WRITEBACK_UUID_FIELD_VALUE:-akeneo_product_uuid}"
RESOURCE_SPACE_WRITEBACK_OWNER_TYPE_FIELD_VALUE="${RESOURCE_SPACE_WRITEBACK_OWNER_TYPE_FIELD_VALUE:-akeneo_owner_type}"
RESOURCE_SPACE_WRITEBACK_LINKS_FIELD_VALUE="${RESOURCE_SPACE_WRITEBACK_LINKS_FIELD_VALUE:-akeneo_links}"

if [[ "$TARGET" =~ ^https?:// ]]; then
  PIM_URL="$TARGET"
  TARGET_HOST="${TARGET#http://}"
  TARGET_HOST="${TARGET_HOST#https://}"
  TARGET_HOST="${TARGET_HOST%%/*}"
  TARGET_HOST="${TARGET_HOST%%:*}"
else
  TARGET_HOST="$TARGET"
  PIM_URL="http://$TARGET"
fi

RESOURCE_SPACE_BASE_URI_VALUE="${RESOURCE_SPACE_BASE_URI_VALUE:-http://${TARGET_HOST}/assets}"
RESOURCE_SPACE_INTERNAL_BASE_URI_VALUE="${RESOURCE_SPACE_INTERNAL_BASE_URI_VALUE:-http://resourcespace}"
MARKETPLACE_ORCHESTRATOR_BASE_URI_VALUE="${MARKETPLACE_ORCHESTRATOR_BASE_URI_VALUE:-http://marketplace-orchestrator:8090}"
MARKETPLACE_ORCHESTRATOR_PUBLIC_BASE_URL_VALUE="${MARKETPLACE_ORCHESTRATOR_PUBLIC_BASE_URL_VALUE:-http://${TARGET_HOST}/market}"
OPERATOR_CONTROL_PLANE_PUBLIC_BASE_URL_VALUE="${OPERATOR_CONTROL_PLANE_PUBLIC_BASE_URL_VALUE:-http://${TARGET_HOST}/control-plane}"
OPERATOR_CONTROL_PLANE_CATALOG_PUBLIC_URL_VALUE="${OPERATOR_CONTROL_PLANE_CATALOG_PUBLIC_URL_VALUE:-$PIM_URL}"
OPERATOR_CONTROL_PLANE_DAM_PUBLIC_URL_VALUE="${OPERATOR_CONTROL_PLANE_DAM_PUBLIC_URL_VALUE:-$RESOURCE_SPACE_BASE_URI_VALUE}"
OPERATOR_CONTROL_PLANE_MARKETPLACE_PUBLIC_URL_VALUE="${OPERATOR_CONTROL_PLANE_MARKETPLACE_PUBLIC_URL_VALUE:-${MARKETPLACE_ORCHESTRATOR_PUBLIC_BASE_URL_VALUE}/dashboard}"
OPERATOR_CONTROL_PLANE_EPIC_AI_PUBLIC_URL_VALUE="${OPERATOR_CONTROL_PLANE_EPIC_AI_PUBLIC_URL_VALUE:-}"
OPERATOR_CONTROL_PLANE_ENVIRONMENT_VALUE="${OPERATOR_CONTROL_PLANE_ENVIRONMENT_VALUE:-prod}"
OPERATOR_CONTROL_PLANE_OPS_BASE_URL_VALUE="${OPERATOR_CONTROL_PLANE_OPS_BASE_URL_VALUE:-http://127.0.0.1/control-plane}"
OPERATOR_CONTROL_PLANE_OPS_TENANT_VALUE="${OPERATOR_CONTROL_PLANE_OPS_TENANT_VALUE:-default}"
OPERATOR_CONTROL_PLANE_PASSWORD_RESET_BASE_URL_VALUE="${OPERATOR_CONTROL_PLANE_PASSWORD_RESET_BASE_URL_VALUE:-$OPERATOR_CONTROL_PLANE_PUBLIC_BASE_URL_VALUE}"
OPERATOR_CONTROL_PLANE_AKENEO_BASE_URL_VALUE="${OPERATOR_CONTROL_PLANE_AKENEO_BASE_URL_VALUE:-http://httpd}"
OPERATOR_CONTROL_PLANE_MARKETPLACE_BASE_URL_VALUE="${OPERATOR_CONTROL_PLANE_MARKETPLACE_BASE_URL_VALUE:-http://marketplace-orchestrator:8090}"
OPERATOR_CONTROL_PLANE_DAM_BASE_URL_VALUE="${OPERATOR_CONTROL_PLANE_DAM_BASE_URL_VALUE:-http://resourcespace}"
OPERATOR_CONTROL_PLANE_EPIC_AI_BASE_URL_VALUE="${OPERATOR_CONTROL_PLANE_EPIC_AI_BASE_URL_VALUE:-http://host.docker.internal:3005}"
LOCAL_PIM_HEALTH_URI="${LOCAL_PIM_HEALTH_URI:-http://127.0.0.1/}"
LOCAL_RESOURCE_SPACE_HEALTH_URI="${LOCAL_RESOURCE_SPACE_HEALTH_URI:-http://127.0.0.1/assets/pages/login.php?no_redirect=true}"
LOCAL_MARKETPLACE_HEALTH_URI="${LOCAL_MARKETPLACE_HEALTH_URI:-http://127.0.0.1/market/health}"
LOCAL_CONTROL_PLANE_HEALTH_URI="${LOCAL_CONTROL_PLANE_HEALTH_URI:-http://127.0.0.1/control-plane/health}"

if [[ -z "$RUNTIME_USER" ]]; then
  if id -u ubuntu >/dev/null 2>&1; then
    RUNTIME_USER="ubuntu"
  else
    RUNTIME_USER="$(id -un)"
  fi
fi

RUNTIME_HOME="${HOME:-}"
if [[ -z "$RUNTIME_HOME" ]]; then
  RUNTIME_HOME="$(getent passwd "$RUNTIME_USER" | cut -d: -f6)"
fi

export HOME="$RUNTIME_HOME"
export USER="$RUNTIME_USER"

dotenv_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

set_env_value() {
  local key="$1"
  local value="$2"
  local escaped_value

  escaped_value="$(dotenv_escape "$value")"

  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${escaped_value}|" "$ENV_FILE"
  else
    printf '\n%s=%s\n' "$key" "$escaped_value" >> "$ENV_FILE"
  fi
}

get_parameter() {
  local name="$1"

  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --with-decryption \
    --name "$name" \
    --query 'Parameter.Value' \
    --output text
}

get_parameter_if_present() {
  local name="$1"

  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --with-decryption \
    --name "$name" \
    --query 'Parameter.Value' \
    --output text 2>/dev/null || true
}

wait_for_http_url() {
  local url="$1"
  local label="$2"
  local attempts="${3:-60}"
  local sleep_seconds="${4:-5}"

  for ((attempt=1; attempt<=attempts; attempt++)); do
    if curl -fsS --max-time 15 "$url" > /dev/null; then
      return 0
    fi

    sleep "$sleep_seconds"
  done

  echo "Timed out waiting for ${label} at ${url}" >&2
  return 1
}

if [[ -n "$DEPLOY_PARAMETER_PREFIX" ]]; then
  APP_SECRET_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/app_secret")"
  APP_DATABASE_PASSWORD_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/app_database_password")"
  APP_DATABASE_ROOT_PASSWORD_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/app_database_root_password")"
  BACKUP_S3_URI_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/backup_s3_uri")"
  MEDIA_BUCKET_VALUE="$(get_parameter_if_present "$DEPLOY_PARAMETER_PREFIX/media_bucket")"
  MEDIA_CDN_BASE_URL_VALUE="$(get_parameter_if_present "$DEPLOY_PARAMETER_PREFIX/media_cdn_base_url")"
  OBJECT_STORAGE_ACCESS_KEY_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/object_storage_access_key")"
  OBJECT_STORAGE_SECRET_KEY_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/object_storage_secret_key")"
  OPERATOR_CONTROL_PLANE_TOKEN_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/operator_control_plane_token")"
  RESOURCE_SPACE_DB_PASSWORD_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/resource_space_db_password")"
  RESOURCE_SPACE_DB_ROOT_PASSWORD_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/resource_space_db_root_password")"
  RESOURCE_SPACE_ADMIN_PASSWORD_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/resource_space_admin_password")"
  RESOURCE_SPACE_SCRAMBLE_KEY_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/resource_space_scramble_key")"
  RESOURCE_SPACE_API_SCRAMBLE_KEY_VALUE="$(get_parameter "$DEPLOY_PARAMETER_PREFIX/resource_space_api_scramble_key")"
fi

RESOURCE_SPACE_API_SCRAMBLE_KEY_VALUE="${RESOURCE_SPACE_API_SCRAMBLE_KEY_VALUE:-coppermind-local-rs-api-scramble-key-2026}"
RESOURCE_SPACE_PRIVATE_API_KEY_VALUE="${RESOURCE_SPACE_API_KEY_VALUE:-$(printf '%s' "${RESOURCE_SPACE_ADMIN_USERNAME_VALUE}${RESOURCE_SPACE_API_SCRAMBLE_KEY_VALUE}" | sha256sum | awk '{print $1}')}"

set_env_value "APP_DATABASE_PASSWORD" "${APP_DATABASE_PASSWORD_VALUE:-akeneo_pim}"
set_env_value "APP_DATABASE_ROOT_PASSWORD" "${APP_DATABASE_ROOT_PASSWORD_VALUE:-root}"
set_env_value "OPERATOR_BACKUP_S3_URI" "${BACKUP_S3_URI_VALUE:-}"
set_env_value "OBJECT_STORAGE_ACCESS_KEY" "${OBJECT_STORAGE_ACCESS_KEY_VALUE:-AKENEO_OBJECT_STORAGE_ACCESS_KEY}"
set_env_value "OBJECT_STORAGE_SECRET_KEY" "${OBJECT_STORAGE_SECRET_KEY_VALUE:-AKENEO_OBJECT_STORAGE_SECRET_KEY}"
set_env_value "OPERATOR_CONTROL_PLANE_TOKEN" "${OPERATOR_CONTROL_PLANE_TOKEN_VALUE:-}"
set_env_value "RESOURCE_SPACE_DB_PASSWORD" "${RESOURCE_SPACE_DB_PASSWORD_VALUE:-change-me}"
set_env_value "RESOURCE_SPACE_DB_ROOT_PASSWORD" "${RESOURCE_SPACE_DB_ROOT_PASSWORD_VALUE:-change-me}"
set_env_value "RESOURCE_SPACE_ADMIN_USERNAME" "$RESOURCE_SPACE_ADMIN_USERNAME_VALUE"
set_env_value "RESOURCE_SPACE_ADMIN_PASSWORD" "${RESOURCE_SPACE_ADMIN_PASSWORD_VALUE:-ShardplatePower13}"
set_env_value "RESOURCE_SPACE_ADMIN_FULLNAME" "$RESOURCE_SPACE_ADMIN_FULLNAME_VALUE"
set_env_value "RESOURCE_SPACE_ADMIN_EMAIL" "$RESOURCE_SPACE_ADMIN_EMAIL_VALUE"
set_env_value "RESOURCE_SPACE_APPLICATION_NAME" "$RESOURCE_SPACE_APPLICATION_NAME_VALUE"
set_env_value "RESOURCE_SPACE_EMAIL_FROM" "$RESOURCE_SPACE_EMAIL_FROM_VALUE"
set_env_value "RESOURCE_SPACE_EMAIL_NOTIFY" "$RESOURCE_SPACE_EMAIL_NOTIFY_VALUE"
set_env_value "RESOURCE_SPACE_BASE_URI" "$RESOURCE_SPACE_BASE_URI_VALUE"
set_env_value "RESOURCE_SPACE_INTERNAL_BASE_URI" "$RESOURCE_SPACE_INTERNAL_BASE_URI_VALUE"
set_env_value "RESOURCE_SPACE_SEARCH_TEMPLATE" "$RESOURCE_SPACE_SEARCH_TEMPLATE_VALUE"
set_env_value "RESOURCE_SPACE_SCRAMBLE_KEY" "${RESOURCE_SPACE_SCRAMBLE_KEY_VALUE:-coppermind-local-rs-scramble-key-2026}"
set_env_value "RESOURCE_SPACE_API_SCRAMBLE_KEY" "$RESOURCE_SPACE_API_SCRAMBLE_KEY_VALUE"
set_env_value "RESOURCE_SPACE_API_USER" "$RESOURCE_SPACE_ADMIN_USERNAME_VALUE"
set_env_value "RESOURCE_SPACE_API_KEY" "$RESOURCE_SPACE_PRIVATE_API_KEY_VALUE"
set_env_value "RESOURCE_SPACE_SEARCH_LIMIT" "$RESOURCE_SPACE_SEARCH_LIMIT_VALUE"
set_env_value "RESOURCE_SPACE_TIMEOUT_SECONDS" "$RESOURCE_SPACE_TIMEOUT_SECONDS_VALUE"
set_env_value "RESOURCE_SPACE_WRITEBACK_ENABLED" "1"
set_env_value "RESOURCE_SPACE_WRITEBACK_IDENTIFIER_FIELD" "$RESOURCE_SPACE_WRITEBACK_IDENTIFIER_FIELD_VALUE"
set_env_value "RESOURCE_SPACE_WRITEBACK_UUID_FIELD" "$RESOURCE_SPACE_WRITEBACK_UUID_FIELD_VALUE"
set_env_value "RESOURCE_SPACE_WRITEBACK_OWNER_TYPE_FIELD" "$RESOURCE_SPACE_WRITEBACK_OWNER_TYPE_FIELD_VALUE"
set_env_value "RESOURCE_SPACE_WRITEBACK_LINKS_FIELD" "$RESOURCE_SPACE_WRITEBACK_LINKS_FIELD_VALUE"
set_env_value "RESOURCE_SPACE_DEFAULT_ATTRIBUTE_CODE" "${RESOURCE_SPACE_DEFAULT_ATTRIBUTE_CODE_VALUE:-}"
set_env_value "COPPERMIND_DEFAULT_TENANT_CODE" "$COPPERMIND_DEFAULT_TENANT_CODE_VALUE"
set_env_value "MARKETPLACE_ORCHESTRATOR_BASE_URI" "$MARKETPLACE_ORCHESTRATOR_BASE_URI_VALUE"
set_env_value "MARKETPLACE_ORCHESTRATOR_PUBLIC_BASE_URL" "$MARKETPLACE_ORCHESTRATOR_PUBLIC_BASE_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_PUBLIC_BASE_URL" "$OPERATOR_CONTROL_PLANE_PUBLIC_BASE_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_CATALOG_PUBLIC_URL" "$OPERATOR_CONTROL_PLANE_CATALOG_PUBLIC_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_DAM_PUBLIC_URL" "$OPERATOR_CONTROL_PLANE_DAM_PUBLIC_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_MARKETPLACE_PUBLIC_URL" "$OPERATOR_CONTROL_PLANE_MARKETPLACE_PUBLIC_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_EPIC_AI_PUBLIC_URL" "$OPERATOR_CONTROL_PLANE_EPIC_AI_PUBLIC_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_ENVIRONMENT" "$OPERATOR_CONTROL_PLANE_ENVIRONMENT_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_OPS_BASE_URL" "$OPERATOR_CONTROL_PLANE_OPS_BASE_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_OPS_TENANT" "$OPERATOR_CONTROL_PLANE_OPS_TENANT_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_PASSWORD_RESET_BASE_URL" "$OPERATOR_CONTROL_PLANE_PASSWORD_RESET_BASE_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_AKENEO_BASE_URL" "$OPERATOR_CONTROL_PLANE_AKENEO_BASE_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_AKENEO_TOKEN" "${OPERATOR_CONTROL_PLANE_AKENEO_TOKEN_VALUE:-${OPERATOR_CONTROL_PLANE_TOKEN_VALUE:-}}"
set_env_value "OPERATOR_CONTROL_PLANE_MARKETPLACE_BASE_URL" "$OPERATOR_CONTROL_PLANE_MARKETPLACE_BASE_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_DAM_BASE_URL" "$OPERATOR_CONTROL_PLANE_DAM_BASE_URL_VALUE"
set_env_value "OPERATOR_CONTROL_PLANE_EPIC_AI_BASE_URL" "$OPERATOR_CONTROL_PLANE_EPIC_AI_BASE_URL_VALUE"
set_env_value "OPERATOR_MEDIA_STORAGE_REGION" "${OPERATOR_MEDIA_STORAGE_REGION_VALUE:-$AWS_REGION}"
set_env_value "OPERATOR_MEDIA_STORAGE_BUCKET" "${OPERATOR_MEDIA_STORAGE_BUCKET_VALUE:-${MEDIA_BUCKET_VALUE:-operator-media}}"
set_env_value "OPERATOR_MEDIA_STORAGE_ENDPOINT" "${OPERATOR_MEDIA_STORAGE_ENDPOINT_VALUE:-}"
set_env_value "OPERATOR_MEDIA_STORAGE_USE_PATH_STYLE_ENDPOINT" "${OPERATOR_MEDIA_STORAGE_USE_PATH_STYLE_ENDPOINT_VALUE:-0}"
set_env_value "OPERATOR_MEDIA_STORAGE_ACCESS_KEY" "${OPERATOR_MEDIA_STORAGE_ACCESS_KEY_VALUE:-}"
set_env_value "OPERATOR_MEDIA_STORAGE_SECRET_KEY" "${OPERATOR_MEDIA_STORAGE_SECRET_KEY_VALUE:-}"
set_env_value "OPERATOR_MEDIA_STORAGE_CDN_BASE_URL" "${OPERATOR_MEDIA_STORAGE_CDN_BASE_URL_VALUE:-${MEDIA_CDN_BASE_URL_VALUE:-}}"

APP_SECRET_VALUE="${APP_SECRET_VALUE:-$(openssl rand -hex 32)}" bash "$PROJECT_ROOT/scripts/aws-first-run.sh" "$TARGET"

custom_migrations=(
  "Pim\\Upgrade\\Schema\\Version_7_0_20260316110000_create_resourcespace_asset_link_table"
  "Pim\\Upgrade\\Schema\\Version_7_0_20260323110000_add_resourcespace_writeback_job_table"
  "Pim\\Upgrade\\Schema\\Version_7_0_20260324110000_add_tenant_scoped_resourcespace_configuration"
  "Pim\\Upgrade\\Schema\\Version_7_0_20260406120000_add_governance_outbox_ingest_tables"
)

# Akeneo's installer baselines every discovered migration as executed on a fresh install.
# Replay only the custom Operator migrations so their schema is actually created.
for migration in "${custom_migrations[@]}"; do
  sg docker -c "cd '$PROJECT_ROOT' && docker compose run -u www-data --rm php php bin/console doctrine:migrations:version '$migration' --delete --env=prod --no-interaction"
done

sg docker -c "cd '$PROJECT_ROOT' && docker compose run -u www-data --rm php php bin/console doctrine:migrations:migrate --env=prod --no-interaction"
sg docker -c "cd '$PROJECT_ROOT' && make resourcespace-up"
sg docker -c "cd '$PROJECT_ROOT' && make marketplace-up"
OPERATOR_CONTROL_PLANE_BUNDLE_URI="$(
  printf '%s' "${OPERATOR_CONTROL_PLANE_BUNDLE_URI_VALUE:-${OPERATOR_CONTROL_PLANE_BUNDLE_URI:-}}"
)" \
OPERATOR_CONTROL_PLANE_APP_DIR="${OPERATOR_CONTROL_PLANE_APP_DIR_VALUE:-${OPERATOR_CONTROL_PLANE_APP_DIR:-/home/ubuntu/operator-control-plane/app}}" \
OPERATOR_CONTROL_PLANE_HEALTHCHECK_URL="http://127.0.0.1:8095/health" \
bash "$PROJECT_ROOT/scripts/operator-control-plane-deploy.sh"
AWS_REGION="$AWS_REGION" BOOTSTRAP_USER="$RUNTIME_USER" bash "$PROJECT_ROOT/scripts/operator-install-ops-cron.sh"

sg docker -c "cd '$PROJECT_ROOT' && docker compose run -u www-data --rm php php bin/console coppermind:resourcespace:tenant:configure --env=prod --no-interaction --tenant='$RESOURCE_SPACE_TENANT_CODE' --label='Operator Default Tenant' --status='active' --enabled=true --base-uri='$RESOURCE_SPACE_BASE_URI_VALUE' --internal-base-uri='$RESOURCE_SPACE_INTERNAL_BASE_URI_VALUE' --api-user='$RESOURCE_SPACE_ADMIN_USERNAME_VALUE' --api-key='$RESOURCE_SPACE_PRIVATE_API_KEY_VALUE' --default-attribute='${RESOURCE_SPACE_DEFAULT_ATTRIBUTE_CODE_VALUE:-}' --writeback-enabled=true --writeback-identifier-field='akeneo_identifier' --writeback-uuid-field='akeneo_product_uuid' --writeback-owner-type-field='akeneo_owner_type' --writeback-links-field='akeneo_links'"

sg docker -c "cd '$PROJECT_ROOT' && docker compose stop php node selenium blackfire pubsub-emulator || true"

wait_for_http_url "$LOCAL_PIM_HEALTH_URI" "Operator PIM"
wait_for_http_url "$LOCAL_RESOURCE_SPACE_HEALTH_URI" "Operator DAM"
wait_for_http_url "$LOCAL_MARKETPLACE_HEALTH_URI" "marketplace orchestrator"
wait_for_http_url "$LOCAL_CONTROL_PLANE_HEALTH_URI" "Operator control plane"

echo "Operator deployment completed."
echo "Operator URL: $PIM_URL"
echo "Assets URL: $RESOURCE_SPACE_BASE_URI_VALUE"
